---

collections:
  - name: https://github.com/cloudera-labs/cloudera.cluster.git
    type: git
    version: devel
  - name: https://github.com/cloudera-labs/cloudera.exe.git
    type: git
    version: devel

roles:
  # Required by cloudera.cluster
  - name: geerlingguy.postgresql
    version: 2.2.0

  # Required by cloudera.cluster
  # geerlingguy.mysql with fix for issue #332
  - src: https://github.com/dbeech/ansible-role-mysql
    version: master
