---

# Copyright 2023 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish a single Execution Environment image

on:
  workflow_dispatch:
    inputs:
      PROFILE:
        description: 'Execution profile'
        default: 'base'
        required: false
        type: choice
        options:
          - base
          - aws
          - azure
          - gcp
          - full

permissions:
  contents: read
  packages: write

jobs:
  publish-base:
    uses: ./.github/workflows/build_push_image.yml
    with:
      PROFILE: base

  publish-profiles:
    if: ${{ inputs.PROFILE != 'base' }}
    needs: publish-base
    uses: ./.github/workflows/build_push_image.yml
    with:
      PROFILE: ${{ inputs.PROFILE }}